### ISSUE TITLE
This is linked in spam?

### ISSUE THREAD

**Issue by lindhe** [kaniini/antissh#1]
Are you aware that this is linked in spam messages now?

![screenshot from 2018-07-29 19-34-17](https://user-images.githubusercontent.com/7773090/43369003-78feb990-9366-11e8-945e-15d545521ec2.png)

**Comment by kaniini** [comment]
they are spamming it in order to discourage network admins from adopting this mitigation.  this software detects and removes the bots which are propagating that spam.
