### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 181: invalid start byte

### ISSUE THREAD

**Issue by Cronus89** [kaniini/antissh#12]
right after the oper is sent get an exception

DEBUG:asyncirc.IRCProtocol:b'PING :GNIP'
DEBUG:asyncirc.IRCProtocol::martini.domain.net PONG martini.domain.net :GNIP
DEBUG:asyncirc.IRCProtocol:b'OPER user passw0rd\r\n'
ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/home/ircd/.local/lib/python3.5/site-packages/asyncirc/irc.py", line 81, in data_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 181: invalid start byte

**Comment by kaniini** [comment]
that's due to `asyncio-irc` library, it shouldn't effect the bot failing to work.  i would suggest reporting it there: https://github.com/watchtower/asyncirc/issues/new
